# Generated by Django 5.2.18 on 2026-10-07 06:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeospatialFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                ("crs", models.CharField(blank=True, default="", max_length=64)),
                ("feature_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeatureRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("feature_index", models.PositiveIntegerField()),
                ("geometry_type", models.CharField(max_length=64)),
                ("geometry", models.JSONField()),
                ("crs", models.CharField(max_length=64)),
                ("properties", models.JSONField(default=dict)),
                (
                    "measurement_type",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("measurement_value", models.FloatField(blank=True, null=True)),
                (
                    "measurement_unit",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "measurement_error",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "geospatial_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="files.geospatialfile",
                    ),
                ),
            ],
            options={
                "ordering": ["feature_index"],
                "unique_together": {("geospatial_file", "feature_index")},
            },
        ),
    ]
